name: Generate Game Blocks

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # Allows manual run from GitHub interface

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Clone GameFiles repo
      run: |
        git clone https://github.com/touchmetender/GameFiles.git GameFiles

    - name: Generate game blocks HTML
      run: |
        mkdir -p generated
        python generate.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add generated/games.html
        git commit -m "Auto-update games.html"
        git push
